// Emoji data with names and categories
export const EMOJI_DATA = {
  recent: {
    name: 'Recently Used',
    icon: 'Clock',
    emojis: [
      { emoji: '😊', name: 'smiling face with smiling eyes' },
      { emoji: '👍', name: 'thumbs up' },
      { emoji: '❤️', name: 'red heart' },
      { emoji: '😂', name: 'face with tears of joy' },
      { emoji: '🔥', name: 'fire' },
      { emoji: '🎉', name: 'party popper' },
      { emoji: '💯', name: 'hundred points' },
      { emoji: '😍', name: 'smiling face with heart-eyes' },
      { emoji: '👏', name: 'clapping hands' },
      { emoji: '🙏', name: 'folded hands' },
      { emoji: '😉', name: 'winking face' },
      { emoji: '🤔', name: 'thinking face' },
      { emoji: '😎', name: 'smiling face with sunglasses' },
      { emoji: '😢', name: 'crying face' },
      { emoji: '😮', name: 'face with open mouth' },
      { emoji: '😴', name: 'sleeping face' },
      { emoji: '🤗', name: 'hugging face' },
      { emoji: '🥰', name: 'smiling face with hearts' },
      { emoji: '😘', name: 'face blowing a kiss' },
      { emoji: '⭐', name: 'star' },
      { emoji: '✨', name: 'sparkles' },
      { emoji: '💕', name: 'two hearts' },
      { emoji: '💖', name: 'sparkling heart' },
      { emoji: '🌟', name: 'glowing star' }
    ]
  },
  smileys: {
    name: 'Smileys & People',
    icon: 'Smile',
    emojis: [
      { emoji: '😀', name: 'grinning face happy smile' },
      { emoji: '😃', name: 'grinning face with big eyes happy smile' },
      { emoji: '😄', name: 'grinning face with smiling eyes happy smile' },
      { emoji: '😁', name: 'beaming face with smiling eyes happy smile' },
      { emoji: '😆', name: 'grinning squinting face happy laugh' },
      { emoji: '😅', name: 'grinning face with sweat nervous laugh' },
      { emoji: '🤣', name: 'rolling on the floor laughing lol rofl' },
      { emoji: '😂', name: 'face with tears of joy laughing cry' },
      { emoji: '🙂', name: 'slightly smiling face smile' },
      { emoji: '🙃', name: 'upside-down face silly' },
      { emoji: '😉', name: 'winking face wink flirty' },
      { emoji: '😊', name: 'smiling face with smiling eyes smile happy' },
      { emoji: '😇', name: 'smiling face with halo innocent angel' },
      { emoji: '🥰', name: 'smiling face with hearts love' },
      { emoji: '😍', name: 'smiling face with heart-eyes love crush' },
      { emoji: '🤩', name: 'star-struck excited amazed' },
      { emoji: '😘', name: 'face blowing a kiss love flirty' },
      { emoji: '😗', name: 'kissing face love' },
      { emoji: '😚', name: 'kissing face with closed eyes love' },
      { emoji: '😙', name: 'kissing face with smiling eyes love' },
      { emoji: '🥲', name: 'smiling face with tear touched grateful' },
      { emoji: '😋', name: 'face savoring food yummy delicious' },
      { emoji: '😛', name: 'face with tongue playful silly' },
      { emoji: '😜', name: 'winking face with tongue playful joke' },
      { emoji: '🤪', name: 'zany face crazy goofy' },
      { emoji: '😝', name: 'squinting face with tongue playful silly' },
      { emoji: '🤑', name: 'money-mouth face rich money' },
      { emoji: '🤗', name: 'hugging face hug' },
      { emoji: '🤭', name: 'face with hand over mouth shocked surprised' },
      { emoji: '🤫', name: 'shushing face quiet silence' },
      { emoji: '🤔', name: 'thinking face think question' },
      { emoji: '🤐', name: 'zipper-mouth face quiet silent' },
      { emoji: '🤨', name: 'face with raised eyebrow skeptical doubt' },
      { emoji: '😐', name: 'neutral face meh' },
      { emoji: '😑', name: 'expressionless face meh' },
      { emoji: '😶', name: 'face without mouth quiet silent' },
      { emoji: '😏', name: 'smirking face smug' },
      { emoji: '😒', name: 'unamused face meh' },
      { emoji: '🙄', name: 'face with rolling eyes eyeroll' },
      { emoji: '😬', name: 'grimacing face awkward' },
      { emoji: '🤥', name: 'lying face liar' },
      { emoji: '😔', name: 'pensive face sad' },
      { emoji: '😪', name: 'sleepy face tired' },
      { emoji: '🤤', name: 'drooling face hungry' },
      { emoji: '😴', name: 'sleeping face sleep tired' },
      { emoji: '😷', name: 'face with medical mask sick' },
      { emoji: '🤒', name: 'face with thermometer sick' },
      { emoji: '🤕', name: 'face with head-bandage hurt' },
      { emoji: '🤢', name: 'nauseated face sick' },
      { emoji: '🤮', name: 'face vomiting sick' },
      { emoji: '🤧', name: 'sneezing face sick' },
      { emoji: '🥵', name: 'hot face sweat' },
      { emoji: '🥶', name: 'cold face freezing' },
      { emoji: '🥴', name: 'woozy face dizzy drunk' },
      { emoji: '😵', name: 'dizzy face dead' },
      { emoji: '🤯', name: 'exploding head mindblown' },
      { emoji: '🤠', name: 'cowboy hat face western' },
      { emoji: '🥳', name: 'partying face celebration birthday' },
      { emoji: '😎', name: 'smiling face with sunglasses cool' },
      { emoji: '🤓', name: 'nerd face glasses' },
      { emoji: '🧐', name: 'face with monocle rich' },
      { emoji: '😕', name: 'confused face confused' },
      { emoji: '😟', name: 'worried face worried' },
      { emoji: '🙁', name: 'slightly frowning face sad' },
      { emoji: '☹️', name: 'frowning face sad' },
      { emoji: '😮', name: 'face with open mouth surprised wow' },
      { emoji: '😯', name: 'hushed face surprised' },
      { emoji: '😲', name: 'astonished face surprised' },
      { emoji: '😳', name: 'flushed face embarrassed' },
      { emoji: '🥺', name: 'pleading face puppyeyes' },
      { emoji: '😦', name: 'frowning face with open mouth sad' },
      { emoji: '😧', name: 'anguished face sad' },
      { emoji: '😨', name: 'fearful face scared' },
      { emoji: '😰', name: 'anxious face with sweat nervous' },
      { emoji: '😥', name: 'sad but relieved face phew' },
      { emoji: '😢', name: 'crying face cry sad' },
      { emoji: '😭', name: 'loudly crying face cry sob' },
      { emoji: '😱', name: 'face screaming in fear scared' },
      { emoji: '😖', name: 'confounded face confused' },
      { emoji: '😣', name: 'persevering face struggling' },
      { emoji: '😞', name: 'disappointed face sad' },
      { emoji: '😓', name: 'downcast face with sweat sad' },
      { emoji: '😩', name: 'weary face tired' },
      { emoji: '😫', name: 'tired face exhausted' },
      { emoji: '🥱', name: 'yawning face tired sleep' },
      { emoji: '😤', name: 'face with steam from nose angry' },
      { emoji: '😡', name: 'pouting face angry mad' },
      { emoji: '😠', name: 'angry face mad' },
      { emoji: '🤬', name: 'face with symbols on mouth cursing' },
      { emoji: '😈', name: 'smiling face with horns devil' },
      { emoji: '👿', name: 'angry face with horns devil' },
      { emoji: '💀', name: 'skull dead' },
      { emoji: '☠️', name: 'skull and crossbones dead' },
      { emoji: '💩', name: 'pile of poo poop' },
      { emoji: '🤡', name: 'clown face silly' },
      { emoji: '👹', name: 'ogre monster' },
      { emoji: '👺', name: 'goblin monster' },
      { emoji: '👻', name: 'ghost halloween' },
      { emoji: '👽', name: 'alien ufo' },
      { emoji: '👾', name: 'alien monster ufo' },
      { emoji: '🤖', name: 'robot face robot' },
      { emoji: '😺', name: 'grinning cat happy' },
      { emoji: '😸', name: 'grinning cat with smiling eyes happy' },
      { emoji: '😹', name: 'cat with tears of joy laughing' },
      { emoji: '😻', name: 'smiling cat with heart-eyes love' },
      { emoji: '😼', name: 'cat with wry smile smug' },
      { emoji: '😽', name: 'kissing cat love' },
      { emoji: '🙀', name: 'weary cat shocked' },
      { emoji: '😿', name: 'crying cat cry sad' },
      { emoji: '😾', name: 'pouting cat angry' },
      { emoji: '👶', name: 'baby child' },
      { emoji: '🧒', name: 'child kid' },
      { emoji: '👦', name: 'boy child' },
      { emoji: '👧', name: 'girl child' },
      { emoji: '🧑', name: 'person adult' },
      { emoji: '👱', name: 'person blond hair' },
      { emoji: '👨', name: 'man adult' },
      { emoji: '🧔', name: 'man beard' },
      { emoji: '👨‍🦰', name: 'man red hair' },
      { emoji: '👨‍🦱', name: 'man curly hair' },
      { emoji: '👨‍🦳', name: 'man white hair' },
      { emoji: '👨‍🦲', name: 'man bald' },
      { emoji: '👩', name: 'woman adult' },
      { emoji: '👩‍🦰', name: 'woman red hair' },
      { emoji: '👩‍🦱', name: 'woman curly hair' },
      { emoji: '👩‍🦳', name: 'woman white hair' },
      { emoji: '👩‍🦲', name: 'woman bald' },
      { emoji: '🧓', name: 'older person elderly' },
      { emoji: '👴', name: 'old man elderly' },
      { emoji: '👵', name: 'old woman elderly' },
      { emoji: '🙍', name: 'person frowning sad' },
      { emoji: '🙎', name: 'person pouting angry' },
      { emoji: '🙅', name: 'person gesturing no stop' },
      { emoji: '🙆', name: 'person gesturing ok okay' },
      { emoji: '💁', name: 'person tipping hand information' },
      { emoji: '🙋', name: 'person raising hand question' },
      { emoji: '🧏', name: 'deaf person hearing disability' },
      { emoji: '🙇', name: 'person bowing respect apology' },
      { emoji: '🤦', name: 'person facepalming disbelief' },
      { emoji: '🤷', name: 'person shrugging doubt' },
      { emoji: '👮', name: 'police officer cop' },
      { emoji: '🕵️', name: 'detective spy' },
      { emoji: '💂', name: 'guard security' },
      { emoji: '🥷', name: 'ninja stealth' },
      { emoji: '👷', name: 'construction worker helmet' },
      { emoji: '🤴', name: 'prince royal' },
      { emoji: '👸', name: 'princess royal' },
      { emoji: '👳', name: 'person wearing turban' },
      { emoji: '👲', name: 'person with skullcap' },
      { emoji: '🧕', name: 'woman with headscarf hijab' },
      { emoji: '🤵', name: 'person in tuxedo groom' },
      { emoji: '👰', name: 'person with veil bride' },
      { emoji: '🤰', name: 'pregnant woman baby' },
      { emoji: '🤱', name: 'breast-feeding baby' },
      { emoji: '👼', name: 'baby angel' },
      { emoji: '🎅', name: 'santa claus christmas' },
      { emoji: '🤶', name: 'mrs claus christmas' },
      { emoji: '🦸', name: 'superhero marvel' },
      { emoji: '🦹', name: 'supervillain marvel' },
      { emoji: '🧙', name: 'mage wizard' },
      { emoji: '🧚', name: 'fairy wings' },
      { emoji: '🧛', name: 'vampire dracula' },
      { emoji: '🧜', name: 'merperson mermaid' },
      { emoji: '🧝', name: 'elf lord of the rings' },
      { emoji: '🧞', name: 'genie wish' },
      { emoji: '🧟', name: 'zombie halloween' },
      { emoji: '💆', name: 'person getting massage relax' },
      { emoji: '💇', name: 'person getting haircut beauty' },
      { emoji: '🚶', name: 'person walking exercise' },
      { emoji: '🧍', name: 'person standing' },
      { emoji: '🧎', name: 'person kneeling' },
      { emoji: '🏃', name: 'person running exercise' },
      { emoji: '💃', name: 'woman dancing dance' },
      { emoji: '🕺', name: 'man dancing dance' },
      { emoji: '🕴️', name: 'person in suit levitating business' },
      { emoji: '👯', name: 'people with bunny ears party' },
      { emoji: '🧖', name: 'person in steamy room sauna' },
      { emoji: '🧗', name: 'person climbing rock' },
      { emoji: '🤺', name: 'person fencing sword' },
      { emoji: '🏇', name: 'horse racing equestrian' },
      { emoji: '⛷️', name: 'skier snow' },
      { emoji: '🏂', name: 'snowboarder snow' },
      { emoji: '🏌️', name: 'person golfing' },
      { emoji: '🏄', name: 'person surfing wave' },
      { emoji: '🚣', name: 'person rowing boat' },
      { emoji: '🏊', name: 'person swimming pool' },
      { emoji: '⛹️', name: 'person bouncing ball basketball' },
      { emoji: '🏋️', name: 'person lifting weights gym' },
      { emoji: '🚴', name: 'person biking bicycle' },
      { emoji: '🚵', name: 'person mountain biking bicycle' },
      { emoji: '🤸', name: 'person cartwheeling gymnastics' },
      { emoji: '🤼', name: 'people wrestling fight' },
      { emoji: '🤽', name: 'person playing water polo' },
      { emoji: '🤾', name: 'person playing handball' },
      { emoji: '🤹', name: 'person juggling circus' },
      { emoji: '🧘', name: 'person in lotus position yoga' },
      { emoji: '🛀', name: 'person taking bath bathtub' },
      { emoji: '🛌', name: 'person in bed sleep' },
      { emoji: '👭', name: 'women holding hands friendship' },
      { emoji: '👫', name: 'woman and man holding hands couple' },
      { emoji: '👬', name: 'men holding hands friendship' },
      { emoji: '💏', name: 'kiss couple' },
      { emoji: '💑', name: 'couple with heart love' },
      { emoji: '👪', name: 'family home' },
      { emoji: '🗣️', name: 'speaking head talk' },
      { emoji: '👤', name: 'bust in silhouette person' },
      { emoji: '👥', name: 'busts in silhouette people' }
    ]
  },
  animals: {
    name: 'Animals & Nature',
    icon: 'Bird',
    emojis: [
      { emoji: '🐶', name: 'dog face puppy pet' },
      { emoji: '🐱', name: 'cat face kitten pet' },
      { emoji: '🐭', name: 'mouse face rodent' },
      { emoji: '🐹', name: 'hamster pet' },
      { emoji: '🐰', name: 'rabbit face bunny' },
      { emoji: '🦊', name: 'fox animal' },
      { emoji: '🐻', name: 'bear animal' },
      { emoji: '🐼', name: 'panda animal' },
      { emoji: '🐨', name: 'koala animal' },
      { emoji: '🐯', name: 'tiger face animal' },
      { emoji: '🦁', name: 'lion animal' },
      { emoji: '🐮', name: 'cow face animal' },
      { emoji: '🐷', name: 'pig face animal' },
      { emoji: '🐸', name: 'frog animal' },
      { emoji: '🐵', name: 'monkey face animal' },
      { emoji: '🐔', name: 'chicken animal' },
      { emoji: '🐧', name: 'penguin animal' },
      { emoji: '🐦', name: 'bird animal' },
      { emoji: '🐤', name: 'baby chick animal' },
      { emoji: '🦆', name: 'duck animal' },
      { emoji: '🦅', name: 'eagle animal' },
      { emoji: '🦉', name: 'owl animal' },
      { emoji: '🦇', name: 'bat animal' },
      { emoji: '🐺', name: 'wolf animal' },
      { emoji: '🐗', name: 'boar animal' },
      { emoji: '🐴', name: 'horse face animal' },
      { emoji: '🦄', name: 'unicorn animal mythical' },
      { emoji: '🐝', name: 'honeybee insect' },
      { emoji: '🐛', name: 'bug insect' },
      { emoji: '🦋', name: 'butterfly insect' },
      { emoji: '🐌', name: 'snail animal' },
      { emoji: '🐞', name: 'lady beetle insect' },
      { emoji: '🐜', name: 'ant insect' },
      { emoji: '🦟', name: 'mosquito insect' },
      { emoji: '🦗', name: 'cricket insect' },
      { emoji: '🕷️', name: 'spider insect' },
      { emoji: '🦂', name: 'scorpion animal' },
      { emoji: '🐢', name: 'turtle animal' },
      { emoji: '🐍', name: 'snake animal' },
      { emoji: '🦎', name: 'lizard animal' },
      { emoji: '🦖', name: 't-rex dinosaur' },
      { emoji: '🦕', name: 'sauropod dinosaur' },
      { emoji: '🐙', name: 'octopus animal' },
      { emoji: '🦑', name: 'squid animal' },
      { emoji: '🦐', name: 'shrimp animal' },
      { emoji: '🦞', name: 'lobster animal' },
      { emoji: '🦀', name: 'crab animal' },
      { emoji: '🐡', name: 'blowfish animal' },
      { emoji: '🐠', name: 'tropical fish animal' },
      { emoji: '🐟', name: 'fish animal' },
      { emoji: '🐬', name: 'dolphin animal' },
      { emoji: '🐳', name: 'spouting whale animal' },
      { emoji: '🐋', name: 'whale animal' },
      { emoji: '🦈', name: 'shark animal' },
      { emoji: '🐊', name: 'crocodile animal' },
      { emoji: '🐅', name: 'tiger animal' },
      { emoji: '🐆', name: 'leopard animal' },
      { emoji: '🦓', name: 'zebra animal' },
      { emoji: '🦍', name: 'gorilla animal' },
      { emoji: '🦧', name: 'orangutan animal' },
      { emoji: '🐘', name: 'elephant animal' },
      { emoji: '🦛', name: 'hippopotamus animal' },
      { emoji: '🦏', name: 'rhinoceros animal' },
      { emoji: '🐪', name: 'camel animal' },
      { emoji: '🐫', name: 'two-hump camel animal' },
      { emoji: '🦒', name: 'giraffe animal' },
      { emoji: '🦘', name: 'kangaroo animal' },
      { emoji: '🐃', name: 'water buffalo animal' },
      { emoji: '🐂', name: 'ox animal' },
      { emoji: '🐄', name: 'cow animal' },
      { emoji: '🐎', name: 'horse animal' },
      { emoji: '🐖', name: 'pig animal' },
      { emoji: '🐏', name: 'ram animal' },
      { emoji: '🐑', name: 'ewe animal' },
      { emoji: '🐐', name: 'goat animal' },
      { emoji: '🦌', name: 'deer animal' },
      { emoji: '🐕', name: 'dog pet' },
      { emoji: '🐩', name: 'poodle dog' },
      { emoji: '🦮', name: 'guide dog assistance' },
      { emoji: '🐕‍🦺', name: 'service dog assistance' },
      { emoji: '🐈', name: 'cat pet' },
      { emoji: '🐓', name: 'rooster chicken' },
      { emoji: '🦃', name: 'turkey bird' },
      { emoji: '🦚', name: 'peacock bird' },
      { emoji: '🦜', name: 'parrot bird' },
      { emoji: '🦢', name: 'swan bird' },
      { emoji: '🦩', name: 'flamingo bird' },
      { emoji: '🕊️', name: 'dove bird peace' },
      { emoji: '🐇', name: 'rabbit animal' },
      { emoji: '🦝', name: 'raccoon animal' },
      { emoji: '🦨', name: 'skunk animal' },
      { emoji: '🦡', name: 'badger animal' },
      { emoji: '🦦', name: 'otter animal' },
      { emoji: '🦥', name: 'sloth animal' },
      { emoji: '🐁', name: 'mouse animal' },
      { emoji: '🐀', name: 'rat animal' },
      { emoji: '🐿️', name: 'chipmunk animal' },
      { emoji: '🦔', name: 'hedgehog animal' },
      { emoji: '🐾', name: 'paw prints animal' },
      { emoji: '🐉', name: 'dragon mythical' },
      { emoji: '🐲', name: 'dragon face mythical' },
      { emoji: '🌵', name: 'cactus plant' },
      { emoji: '🎄', name: 'christmas tree holiday' },
      { emoji: '🌲', name: 'evergreen tree plant' },
      { emoji: '🌳', name: 'deciduous tree plant' },
      { emoji: '🌴', name: 'palm tree plant' },
      { emoji: '🌱', name: 'seedling plant' },
      { emoji: '🌿', name: 'herb plant' },
      { emoji: '☘️', name: 'shamrock plant' },
      { emoji: '🍀', name: 'four leaf clover plant' },
      { emoji: '🎍', name: 'pine decoration plant' },
      { emoji: '🎋', name: 'tanabata tree plant' },
      { emoji: '🍃', name: 'leaf fluttering in wind plant' },
      { emoji: '🍂', name: 'fallen leaf plant' },
      { emoji: '🍁', name: 'maple leaf plant' },
      { emoji: '🍄', name: 'mushroom plant' },
      { emoji: '🌾', name: 'sheaf of rice plant' },
      { emoji: '💐', name: 'bouquet flowers' },
      { emoji: '🌷', name: 'Tulip flower' },
      { emoji: '🌹', name: 'rose flower' },
      { emoji: '🥀', name: 'wilted flower plant' },
      { emoji: '🌺', name: 'hibiscus flower' },
      { emoji: '🌸', name: 'cherry blossom flower' },
      { emoji: '🌼', name: 'blossom flower' },
      { emoji: '🌻', name: 'sunflower flower' },
      { emoji: '🌞', name: 'sun with face weather' },
      { emoji: '🌝', name: 'full moon face weather' },
      { emoji: '🌛', name: 'first quarter moon face weather' },
      { emoji: '🌜', name: 'last quarter moon face weather' },
      { emoji: '🌚', name: 'new moon face weather' },
      { emoji: '🌕', name: 'full moon weather' },
      { emoji: '🌖', name: 'waning gibbous moon weather' },
      { emoji: '🌗', name: 'last quarter moon weather' },
      { emoji: '🌘', name: 'waning crescent moon weather' },
      { emoji: '🌑', name: 'new moon weather' },
      { emoji: '🌒', name: 'waxing crescent moon weather' },
      { emoji: '🌓', name: 'first quarter moon weather' },
      { emoji: '🌔', name: 'waxing gibbous moon weather' },
      { emoji: '🌙', name: 'crescent moon weather' },
      { emoji: '🌎', name: 'globe showing europe-africa earth' },
      { emoji: '🌍', name: 'globe showing americas earth' },
      { emoji: '🌏', name: 'globe showing asia-australia earth' },
      { emoji: '🪐', name: 'ringed planet saturn' },
      { emoji: '💫', name: 'dizzy stars animation' },
      { emoji: '⭐', name: 'star weather' },
      { emoji: '🌟', name: 'glowing star weather' },
      { emoji: '✨', name: 'sparkles stars' },
      { emoji: '⚡', name: 'high voltage lightning' },
      { emoji: '🔥', name: 'fire hot' },
      { emoji: '💥', name: 'collision boom' },
      { emoji: '☄️', name: 'comet space' },
      { emoji: '☀️', name: 'sun weather' },
      { emoji: '🌤️', name: 'sun behind small cloud weather' },
      { emoji: '⛅', name: 'sun behind cloud weather' },
      { emoji: '🌥️', name: 'sun behind large cloud weather' },
      { emoji: '🌦️', name: 'sun behind rain cloud weather' },
      { emoji: '🌈', name: 'rainbow weather' },
      { emoji: '☁️', name: 'cloud weather' },
      { emoji: '🌧️', name: 'cloud with rain weather' },
      { emoji: '⛈️', name: 'cloud with lightning and rain weather' },
      { emoji: '🌩️', name: 'cloud with lightning weather' },
      { emoji: '🌨️', name: 'cloud with snow weather' },
      { emoji: '❄️', name: 'snowflake weather' },
      { emoji: '☃️', name: 'snowman weather' },
      { emoji: '⛄', name: 'snowman without snow weather' },
      { emoji: '💧', name: 'droplet water' },
      { emoji: '💦', name: 'sweat droplets water' },
      { emoji: '☔', name: 'umbrella with rain drops weather' },
      { emoji: '🍏', name: 'green apple fruit' },
      { emoji: '🍎', name: 'red apple fruit' },
      { emoji: '🍐', name: 'pear fruit' },
      { emoji: '🍊', name: 'tangerine fruit' },
      { emoji: '🍋', name: 'lemon fruit' },
      { emoji: '🍌', name: 'banana fruit' },
      { emoji: '🍉', name: 'watermelon fruit' },
      { emoji: '🍇', name: 'grapes fruit' },
      { emoji: '🍓', name: 'strawberry fruit' },
      { emoji: '🍈', name: 'melon fruit' },
      { emoji: '🍒', name: 'cherries fruit' },
      { emoji: '🍑', name: 'peach fruit' },
      { emoji: '🥭', name: 'mango fruit' },
      { emoji: '🍍', name: 'pineapple fruit' },
      { emoji: '🥥', name: 'coconut fruit' },
      { emoji: '🥝', name: 'kiwi fruit' },
      { emoji: '🍅', name: 'tomato fruit' },
      { emoji: '🍆', name: 'eggplant vegetable' },
      { emoji: '🥑', name: 'avocado fruit' },
      { emoji: '🥦', name: 'broccoli vegetable' },
      { emoji: '🥬', name: 'leafy green vegetable' },
      { emoji: '🥒', name: 'cucumber vegetable' },
      { emoji: '🌶', name: 'hot pepper vegetable' },
      { emoji: '🌽', name: 'ear of corn vegetable' },
      { emoji: '🥕', name: 'carrot vegetable' },
      { emoji: '🧄', name: 'garlic vegetable' },
      { emoji: '🧅', name: 'onion vegetable' },
      { emoji: '🥔', name: 'potato vegetable' },
      { emoji: '🍠', name: 'roasted sweet potato vegetable' },
      { emoji: '🥐', name: 'croissant bread' },
      { emoji: '🥯', name: 'bagel bread' },
      { emoji: '🍞', name: 'bread loaf' },
      { emoji: '🥖', name: 'baguette bread' },
      { emoji: '🥨', name: 'pretzel bread' },
      { emoji: '🧀', name: 'cheese wedge dairy' },
      { emoji: '🥚', name: 'egg food' },
      { emoji: '🍳', name: 'cooking food' },
      { emoji: '🧈', name: 'butter dairy' },
      { emoji: '🥞', name: 'pancakes food' },
      { emoji: '🧇', name: 'waffle food' },
      { emoji: '🥓', name: 'bacon food' },
      { emoji: '🥩', name: 'cut of meat food' },
      { emoji: '🍗', name: 'poultry leg food' },
      { emoji: '🍖', name: 'meat on bone food' },
      { emoji: '🦴', name: 'bone food' },
      { emoji: '🌭', name: 'hot dog food' },
      { emoji: '🍔', name: 'hamburger food' },
      { emoji: '🍟', name: 'french fries food' },
      { emoji: '🍕', name: 'pizza food' },
      { emoji: '🥪', name: 'sandwich food' },
      { emoji: '🥙', name: 'stuffed flatbread food' },
      { emoji: '🧆', name: 'falafel food' },
      { emoji: '🌮', name: 'taco food' },
      { emoji: '🌯', name: 'burrito food' },
      { emoji: '🥗', name: 'green salad food' },
      { emoji: '🥘', name: 'shallow pan of food food' },
      { emoji: '🍝', name: 'spaghetti food' },
      { emoji: '🍜', name: 'steaming bowl food' },
      { emoji: '🍲', name: 'pot of food food' },
      { emoji: '🍛', name: 'curry rice food' },
      { emoji: '🍣', name: 'sushi food' },
      { emoji: '🍱', name: 'bento box food' },
      { emoji: '🥟', name: 'dumpling food' },
      { emoji: '🦪', name: 'oyster food' },
      { emoji: '🍤', name: 'fried shrimp food' },
      { emoji: '🍙', name: 'rice ball food' },
      { emoji: '🍚', name: 'cooked rice food' },
      { emoji: '🍘', name: 'rice cracker food' },
      { emoji: '🍥', name: 'fish cake with swirl food' },
      { emoji: '🥠', name: 'fortune cookie food' },
      { emoji: '🥮', name: 'moon cake food' },
      { emoji: '🍢', name: 'oden food' },
      { emoji: '🍡', name: 'dango food' },
      { emoji: '🍧', name: 'shaved ice dessert' },
      { emoji: '🍨', name: 'ice cream dessert' },
      { emoji: '🍦', name: 'soft ice cream dessert' },
      { emoji: '🥧', name: 'pie dessert' },
      { emoji: '🧁', name: 'cupcake dessert' },
      { emoji: '🍰', name: 'shortcake dessert' },
      { emoji: '🎂', name: 'birthday cake dessert' },
      { emoji: '🍮', name: 'custard dessert' },
      { emoji: '🍭', name: 'lollipop candy' },
      { emoji: '🍬', name: 'candy sweet' },
      { emoji: '🍫', name: 'chocolate bar sweet' },
      { emoji: '🍿', name: 'popcorn snack' },
      { emoji: '🍩', name: 'doughnut sweet' },
      { emoji: '🍪', name: 'cookie sweet' },
      { emoji: '🌰', name: 'chestnut food' },
      { emoji: '🥜', name: 'peanuts food' },
      { emoji: '🍯', name: 'honey pot food' },
      { emoji: '🥛', name: 'glass of milk drink' },
      { emoji: '🍼', name: 'baby bottle drink' },
      { emoji: '☕', name: 'hot beverage coffee tea' },
      { emoji: '🍵', name: 'teacup without handle drink' },
      { emoji: '🥤', name: 'cup with straw drink' },
      { emoji: '🍶', name: 'sake drink' },
      { emoji: '🍺', name: 'beer mug drink' },
      { emoji: '🍻', name: 'clinking beer mugs drink' },
      { emoji: '🥂', name: 'clinking glasses drink' },
      { emoji: '🍷', name: 'wine glass drink' },
      { emoji: '🥃', name: 'tumbler glass drink' },
      { emoji: '🍸', name: 'cocktail glass drink' },
      { emoji: '🍹', name: 'tropical drink cocktail' },
      { emoji: '🍾', name: 'bottle with popping cork drink' },
      { emoji: '🧊', name: 'ice cube cold' },
      { emoji: '🥄', name: 'spoon utensil' },
      { emoji: '🍴', name: 'fork and knife utensil' },
      { emoji: '🍽️', name: 'fork and knife with plate utensil' },
      { emoji: '🥣', name: 'bowl with spoon food' },
      { emoji: '🥡', name: 'takeout box food' },
      { emoji: '🥢', name: 'chopsticks utensil' },
      { emoji: '🧂', name: 'salt condiment' }
    ]
  },
  food: {
    name: 'Food & Drink',
    icon: 'Utensils',
    emojis: [
      { emoji: '🍏', name: 'green apple fruit healthy' },
      { emoji: '🍎', name: 'red apple fruit healthy' },
      { emoji: '🍐', name: 'pear fruit healthy' },
      { emoji: '🍊', name: 'tangerine orange fruit citrus' },
      { emoji: '🍋', name: 'lemon fruit citrus yellow sour' },
      { emoji: '🍌', name: 'banana fruit yellow healthy' },
      { emoji: '🍉', name: 'watermelon fruit summer red green' },
      { emoji: '🍇', name: 'grapes fruit purple wine' },
      { emoji: '🍓', name: 'strawberry fruit red berry' },
      { emoji: '🍈', name: 'melon fruit green honeydew' },
      { emoji: '🍒', name: 'cherries fruit red berry' },
      { emoji: '🍑', name: 'peach fruit orange fuzzy' },
      { emoji: '🥭', name: 'mango fruit tropical yellow' },
      { emoji: '🍍', name: 'pineapple fruit tropical spiky' },
      { emoji: '🥥', name: 'coconut fruit tropical brown' },
      { emoji: '🥝', name: 'kiwi fruit green fuzzy healthy' },
      { emoji: '🍅', name: 'tomato vegetable red fruit' },
      { emoji: '🍆', name: 'eggplant vegetable purple aubergine' },
      { emoji: '🥑', name: 'avocado fruit green healthy' },
      { emoji: '🥦', name: 'broccoli vegetable green healthy' },
      { emoji: '🥬', name: 'leafy green lettuce salad vegetable' },
      { emoji: '🥒', name: 'cucumber vegetable green fresh' },
      { emoji: '🌶', name: 'hot pepper spicy chili vegetable' },
      { emoji: '🌽', name: 'ear of corn vegetable yellow' },
      { emoji: '🥕', name: 'carrot vegetable orange healthy' },
      { emoji: '🧄', name: 'garlic vegetable cooking spice' },
      { emoji: '🧅', name: 'onion vegetable cooking spice' },
      { emoji: '🥔', name: 'potato vegetable cooking' },
      { emoji: '🍠', name: 'roasted sweet potato vegetable' },
      { emoji: '🥐', name: 'croissant bread pastry breakfast' },
      { emoji: '🥯', name: 'bagel bread breakfast' },
      { emoji: '🍞', name: 'bread loaf bakery' },
      { emoji: '🥖', name: 'baguette bread french' },
      { emoji: '🥨', name: 'pretzel bread twisted' },
      { emoji: '🧀', name: 'cheese wedge dairy' },
      { emoji: '🥚', name: 'egg food breakfast' },
      { emoji: '🍳', name: 'cooking pan breakfast' },
      { emoji: '🧈', name: 'butter dairy' },
      { emoji: '🥞', name: 'pancakes breakfast food' },
      { emoji: '🧇', name: 'waffle breakfast food' },
      { emoji: '🥓', name: 'bacon breakfast meat' },
      { emoji: '🥩', name: 'cut of meat steak beef' },
      { emoji: '🍗', name: 'poultry leg chicken turkey' },
      { emoji: '🍖', name: 'meat on bone steak' },
      { emoji: '🦴', name: 'bone food' },
      { emoji: '🌭', name: 'hot dog sausage food' },
      { emoji: '🍔', name: 'hamburger burger fast food' },
      { emoji: '🍟', name: 'french fries chips fast food' },
      { emoji: '🍕', name: 'pizza food italian' },
      { emoji: '🥪', name: 'sandwich food lunch' },
      { emoji: '🥙', name: 'stuffed flatbread wrap food' },
      { emoji: '🧆', name: 'falafel food middle eastern' },
      { emoji: '🌮', name: 'taco mexican food' },
      { emoji: '🌯', name: 'burrito mexican food' },
      { emoji: '🥗', name: 'green salad healthy food' },
      { emoji: '🥘', name: 'shallow pan of food cooking' },
      { emoji: '🍝', name: 'spaghetti pasta italian' },
      { emoji: '🍜', name: 'steaming bowl ramen noodles' },
      { emoji: '🍲', name: 'pot of food soup stew' },
      { emoji: '🍛', name: 'curry rice food indian' },
      { emoji: '🍣', name: 'sushi japanese food' },
      { emoji: '🍱', name: 'bento box japanese food' },
      { emoji: '🥟', name: 'dumpling food asian' },
      { emoji: '🦪', name: 'oyster seafood' },
      { emoji: '🍤', name: 'fried shrimp seafood' },
      { emoji: '🍙', name: 'rice ball japanese food' },
      { emoji: '🍚', name: 'cooked rice food' },
      { emoji: '🍘', name: 'rice cracker japanese' },
      { emoji: '🍥', name: 'fish cake with swirl japanese' },
      { emoji: '🥠', name: 'fortune cookie dessert' },
      { emoji: '🥮', name: 'moon cake dessert asian' },
      { emoji: '🍢', name: 'oden japanese food' },
      { emoji: '🍡', name: 'dango japanese dessert' },
      { emoji: '🍧', name: 'shaved ice dessert' },
      { emoji: '🍨', name: 'ice cream dessert' },
      { emoji: '🍦', name: 'soft ice cream dessert' },
      { emoji: '🥧', name: 'pie dessert' },
      { emoji: '🧁', name: 'cupcake dessert' },
      { emoji: '🍰', name: 'shortcake dessert' },
      { emoji: '🎂', name: 'birthday cake dessert celebration' },
      { emoji: '🍮', name: 'custard dessert' },
      { emoji: '🍭', name: 'lollipop candy sweet' },
      { emoji: '🍬', name: 'candy sweet' },
      { emoji: '🍫', name: 'chocolate bar sweet' },
      { emoji: '🍿', name: 'popcorn snack movie' },
      { emoji: '🍩', name: 'doughnut dessert sweet' },
      { emoji: '🍪', name: 'cookie dessert sweet' },
      { emoji: '🌰', name: 'chestnut nut' },
      { emoji: '🥜', name: 'peanuts nut' },
      { emoji: '🍯', name: 'honey pot sweet' },
      { emoji: '🥛', name: 'glass of milk drink dairy' },
      { emoji: '🍼', name: 'baby bottle milk' },
      { emoji: '☕', name: 'hot beverage coffee tea' },
      { emoji: '🍵', name: 'teacup without handle tea' },
      { emoji: '🥤', name: 'cup with straw drink' },
      { emoji: '🍶', name: 'sake drink alcohol' },
      { emoji: '🍺', name: 'beer mug drink alcohol' },
      { emoji: '🍻', name: 'clinking beer mugs drink alcohol' },
      { emoji: '🥂', name: 'clinking glasses drink alcohol' },
      { emoji: '🍷', name: 'wine glass drink alcohol' },
      { emoji: '🥃', name: 'tumbler glass drink alcohol' },
      { emoji: '🍸', name: 'cocktail glass drink alcohol' },
      { emoji: '🍹', name: 'tropical drink cocktail alcohol' },
      { emoji: '🍾', name: 'bottle with popping cork champagne' },
      { emoji: '🧊', name: 'ice cube cold' },
      { emoji: '🥄', name: 'spoon utensil' },
      { emoji: '🍴', name: 'fork and knife utensil' },
      { emoji: '🍽️', name: 'fork and knife with plate utensil' },
      { emoji: '🥣', name: 'bowl with spoon food' },
      { emoji: '🥡', name: 'takeout box food' },
      { emoji: '🥢', name: 'chopsticks utensil' },
      { emoji: '🧂', name: 'salt condiment' }
    ]
  },
  activities: {
    name: 'Activities',
    icon: 'Gamepad2',
    emojis: [
      { emoji: '⚽', name: 'soccer ball football sport' },
      { emoji: '🏀', name: 'basketball sport ball' },
      { emoji: '🏈', name: 'american football sport ball' },
      { emoji: '⚾', name: 'baseball sport ball' },
      { emoji: '🥎', name: 'softball sport ball' },
      { emoji: '🎾', name: 'tennis sport ball racket' },
      { emoji: '🏐', name: 'volleyball sport ball' },
      { emoji: '🏉', name: 'rugby football sport ball' },
      { emoji: '🥏', name: 'flying disc frisbee sport' },
      { emoji: '🎱', name: 'pool 8 ball billiards game' },
      { emoji: '🪀', name: 'yo-yo toy game' },
      { emoji: '🏓', name: 'ping pong table tennis sport' },
      { emoji: '🏸', name: 'badminton sport racket' },
      { emoji: '🏒', name: 'ice hockey sport puck' },
      { emoji: '🏑', name: 'field hockey sport stick' },
      { emoji: '🥍', name: 'lacrosse sport stick ball' },
      { emoji: '🏏', name: 'cricket game sport bat' },
      { emoji: '🪃', name: 'boomerang toy game' },
      { emoji: '🥅', name: 'goal net sport soccer' },
      { emoji: '⛳', name: 'golf sport club ball' },
      { emoji: '🪁', name: 'kite toy flying' },
      { emoji: '🏹', name: 'bow and arrow archery sport' },
      { emoji: '🎣', name: 'fishing pole hobby sport' },
      { emoji: '🤿', name: 'diving mask scuba swimming' },
      { emoji: '🥊', name: 'boxing glove sport fight' },
      { emoji: '🥋', name: 'martial arts uniform karate sport' },
      { emoji: '🎽', name: 'running shirt sport exercise' },
      { emoji: '🛹', name: 'skateboard sport extreme' },
      { emoji: '🛼', name: 'roller skate sport fun' },
      { emoji: '⛸', name: 'ice skate sport winter' },
      { emoji: '🥌', name: 'curling stone sport winter' },
      { emoji: '🎿', name: 'skis sport winter' },
      { emoji: '⛷️', name: 'skier sport winter' },
      { emoji: '🏂', name: 'snowboarder sport winter' },
      { emoji: '🏌️', name: 'person golfing sport' },
      { emoji: '🏄', name: 'person surfing sport wave' },
      { emoji: '🚣', name: 'person rowing boat sport' },
      { emoji: '🏊', name: 'person swimming sport pool' },
      { emoji: '⛹️', name: 'person bouncing ball basketball sport' },
      { emoji: '🏋️', name: 'person lifting weights gym sport' },
      { emoji: '🚴', name: 'person biking bicycle sport' },
      { emoji: '🚵', name: 'person mountain biking bicycle sport' },
      { emoji: '🤸', name: 'person cartwheeling gymnastics sport' },
      { emoji: '🤼', name: 'people wrestling sport fight' },
      { emoji: '🤽', name: 'person playing water polo sport' },
      { emoji: '🤾', name: 'person playing handball sport' },
      { emoji: '🤹', name: 'person juggling circus sport' },
      { emoji: '🎪', name: 'circus tent entertainment' },
      { emoji: '🎭', name: 'performing arts theater' },
      { emoji: '🩰', name: 'ballet shoes dance' },
      { emoji: '🎨', name: 'artist palette painting art' },
      { emoji: '🎬', name: 'clapper board movie film' },
      { emoji: '🎤', name: 'microphone singing music' },
      { emoji: '🎧', name: 'headphones music audio' },
      { emoji: '🎼', name: 'musical score music' },
      { emoji: '🎹', name: 'musical keyboard piano' },
      { emoji: '🥁', name: 'drum music instrument' },
      { emoji: '🎷', name: 'saxophone music instrument' },
      { emoji: '🎺', name: 'trumpet music instrument' },
      { emoji: '🎸', name: 'guitar music instrument' },
      { emoji: '🎻', name: 'violin music instrument' },
      { emoji: '🎲', name: 'game die dice' },
      { emoji: '♟️', name: 'chess pawn game' },
      { emoji: '🎯', name: 'bullseye dart game' },
      { emoji: '🎳', name: 'bowling ball game sport' },
      { emoji: '🎮', name: 'video game controller gaming' },
      { emoji: '🕹️', name: 'joystick gaming' },
      { emoji: '🎰', name: 'slot machine casino' },
      { emoji: '🧩', name: 'puzzle piece game' },
      { emoji: '🧸', name: 'teddy bear toy' },
      { emoji: '🪅', name: 'piñata party celebration' },
      { emoji: '🪆', name: 'nesting dolls toy' },
      { emoji: '♠️', name: 'spade suit card' },
      { emoji: '♥️', name: 'heart suit card' },
      { emoji: '♦️', name: 'diamond suit card' },
      { emoji: '♣️', name: 'club suit card' },
      { emoji: '🃏', name: 'joker card game' },
      { emoji: '🀄', name: 'mahjong red dragon game' },
      { emoji: '🎴', name: 'flower playing cards game' }
    ]
  },
  travel: {
    name: 'Travel & Places',
    icon: 'Car',
    emojis: [
      { emoji: '🚗', name: 'automobile car vehicle transport' },
      { emoji: '🚕', name: 'taxi cab car transport' },
      { emoji: '🚙', name: 'sport utility vehicle suv car' },
      { emoji: '🚌', name: 'bus vehicle transport' },
      { emoji: '🚎', name: 'trolleybus bus transport' },
      { emoji: '🏎', name: 'racing car formula1 f1' },
      { emoji: '🚓', name: 'police car cop vehicle' },
      { emoji: '🚑', name: 'ambulance emergency vehicle' },
      { emoji: '🚒', name: 'fire engine truck emergency' },
      { emoji: '🚐', name: 'minibus van transport' },
      { emoji: '🚚', name: 'delivery truck vehicle' },
      { emoji: '🚛', name: 'articulated lorry truck' },
      { emoji: '🚜', name: 'tractor farm vehicle' },
      { emoji: '🛴', name: 'kick scooter transport' },
      { emoji: '🚲', name: 'bicycle bike transport' },
      { emoji: '🛵', name: 'motor scooter transport' },
      { emoji: '🏍', name: 'motorcycle bike transport' },
      { emoji: '🚨', name: 'police car light siren emergency' },
      { emoji: '🚔', name: 'oncoming police car vehicle' },
      { emoji: '🚍', name: 'oncoming bus transport' },
      { emoji: '🚘', name: 'oncoming automobile car' },
      { emoji: '🚖', name: 'oncoming taxi cab' },
      { emoji: '🚡', name: 'aerial tramway cable car' },
      { emoji: '🚠', name: 'mountain cableway transport' },
      { emoji: '🚟', name: 'suspension railway transport' },
      { emoji: '🚃', name: 'railway car train' },
      { emoji: '🚋', name: 'tram car transport' },
      { emoji: '🚞', name: 'mountain railway train' },
      { emoji: '🚝', name: 'monorail train transport' },
      { emoji: '🚄', name: 'high-speed train bullet' },
      { emoji: '🚅', name: 'bullet train fast' },
      { emoji: '🚈', name: 'light rail train' },
      { emoji: '🚂', name: 'locomotive train' },
      { emoji: '🚆', name: 'train railway' },
      { emoji: '🚇', name: 'metro subway underground' },
      { emoji: '🚊', name: 'tram streetcar' },
      { emoji: '🚉', name: 'station train railway' },
      { emoji: '🚁', name: 'helicopter aircraft' },
      { emoji: '🚟', name: 'suspension railway' },
      { emoji: '🚞', name: 'mountain railway' },
      { emoji: '🚝', name: 'monorail' },
      { emoji: '✈️', name: 'airplane aircraft flight' },
      { emoji: '🛩️', name: 'small airplane aircraft' },
      { emoji: '🛫', name: 'airplane departure flight' },
      { emoji: '🛬', name: 'airplane arrival flight' },
      { emoji: '🪂', name: 'parachute skydiving' },
      { emoji: '💺', name: 'seat chair' },
      { emoji: '🚀', name: 'rocket space' },
      { emoji: '🛸', name: 'flying saucer ufo alien' },
      { emoji: '🚁', name: 'helicopter' },
      { emoji: '🚟', name: 'suspension railway' },
      { emoji: '🚞', name: 'mountain railway' },
      { emoji: '🚝', name: 'monorail' },
      { emoji: '⛵', name: 'sailboat boat' },
      { emoji: '🛶', name: 'canoe boat' },
      { emoji: '🚤', name: 'speedboat boat' },
      { emoji: '🛳️', name: 'passenger ship cruise' },
      { emoji: '⛴️', name: 'ferry boat' },
      { emoji: '🛥️', name: 'motor boat' },
      { emoji: '🚢', name: 'ship boat cruise' },
      { emoji: '⚓', name: 'anchor boat' },
      { emoji: '⛽', name: 'fuel pump gas station' },
      { emoji: '🚨', name: 'police car light' },
      { emoji: '🚥', name: 'horizontal traffic light' },
      { emoji: '🚦', name: 'vertical traffic light' },
      { emoji: '🛑', name: 'stop sign traffic' },
      { emoji: '🚧', name: 'construction sign' },
      { emoji: '🛤️', name: 'railway track train' },
      { emoji: '🛣️', name: 'motorway highway road' },
      { emoji: '🗺️', name: 'map geography' },
      { emoji: '⛽', name: 'fuel pump' },
      { emoji: '🚨', name: 'police car light' },
      { emoji: '🚥', name: 'horizontal traffic light' },
      { emoji: '🚦', name: 'vertical traffic light' },
      { emoji: '🛑', name: 'stop sign' },
      { emoji: '🚧', name: 'construction' },
      { emoji: '🛤️', name: 'railway track' },
      { emoji: '🛣️', name: 'motorway' },
      { emoji: '🗺️', name: 'map' },
      { emoji: '🗿', name: 'moai statue' },
      { emoji: '🗽', name: 'statue of liberty landmark' },
      { emoji: '🗼', name: 'tokyo tower landmark' },
      { emoji: '🏰', name: 'castle building' },
      { emoji: '🏯', name: 'japanese castle building' },
      { emoji: '🏟️', name: 'stadium sport' },
      { emoji: '🎡', name: 'ferris wheel amusement park' },
      { emoji: '🎢', name: 'roller coaster amusement park' },
      { emoji: '🎠', name: 'carousel horse amusement' },
      { emoji: '⛲', name: 'fountain water' },
      { emoji: '⛹️', name: 'person bouncing ball' },
      { emoji: '🏋️', name: 'person lifting weights' },
      { emoji: '🚴', name: 'person biking' },
      { emoji: '🚵', name: 'person mountain biking' },
      { emoji: '🤸', name: 'person cartwheeling' },
      { emoji: '🤼', name: 'people wrestling' },
      { emoji: '🤽', name: 'person playing water polo' },
      { emoji: '🤾', name: 'person playing handball' },
      { emoji: '🤹', name: 'person juggling' },
      { emoji: '🎪', name: 'circus tent' },
      { emoji: '🎭', name: 'performing arts' },
      { emoji: '🩰', name: 'ballet shoes' },
      { emoji: '🎨', name: 'artist palette' },
      { emoji: '🎬', name: 'clapper board' },
      { emoji: '🎤', name: 'microphone' },
      { emoji: '🎧', name: 'headphones' },
      { emoji: '🎼', name: 'musical score' },
      { emoji: '🎹', name: 'musical keyboard' },
      { emoji: '🥁', name: 'drum' },
      { emoji: '🎷', name: 'saxophone' },
      { emoji: '🎺', name: 'trumpet' },
      { emoji: '🎸', name: 'guitar' },
      { emoji: '🎻', name: 'violin' },
      { emoji: '🎲', name: 'game die' },
      { emoji: '♟️', name: 'chess pawn' },
      { emoji: '🎯', name: 'bullseye' },
      { emoji: '🎳', name: 'bowling' },
      { emoji: '🎮', name: 'video game' },
      { emoji: '🕹️', name: 'joystick' },
      { emoji: '🎰', name: 'slot machine' },
      { emoji: '🧩', name: 'puzzle piece' },
      { emoji: '🧸', name: 'teddy bear' },
      { emoji: '🪅', name: 'piñata' },
      { emoji: '🪆', name: 'nesting dolls' },
      { emoji: '♠️', name: 'spade suit' },
      { emoji: '♥️', name: 'heart suit' },
      { emoji: '♦️', name: 'diamond suit' },
      { emoji: '♣️', name: 'club suit' },
      { emoji: '🃏', name: 'joker' },
      { emoji: '🀄', name: 'mahjong red dragon' },
      { emoji: '🎴', name: 'flower playing cards' }
    ]
  },
  objects: {
    name: 'Objects',
    icon: 'Package',
    emojis: [
      { emoji: '⌚', name: 'watch time' },
      { emoji: '📱', name: 'mobile phone smartphone' },
      { emoji: '📲', name: 'mobile phone with arrow' },
      { emoji: '💻', name: 'laptop computer' },
      { emoji: '⌨️', name: 'keyboard typing' },
      { emoji: '🖥️', name: 'desktop computer monitor' },
      { emoji: '🖨️', name: 'printer office' },
      { emoji: '🖱️', name: 'computer mouse' },
      { emoji: '🖲️', name: 'trackball' },
      { emoji: '🕹️', name: 'joystick gaming' },
      { emoji: '🗜️', name: 'clamp tool' },
      { emoji: '💽', name: 'computer disk storage' },
      { emoji: '💾', name: 'floppy disk save' },
      { emoji: '💿', name: 'optical disk cd' },
      { emoji: '📀', name: 'dvd disc' },
      { emoji: '📼', name: 'videocassette tape' },
      { emoji: '📷', name: 'camera photography' },
      { emoji: '📸', name: 'camera with flash' },
      { emoji: '📹', name: 'video camera recording' },
      { emoji: '🎥', name: 'movie camera film' },
      { emoji: '📽️', name: 'film projector' },
      { emoji: '🎞️', name: 'film frames' },
      { emoji: '📞', name: 'telephone receiver phone' },
      { emoji: '☎️', name: 'telephone landline' },
      { emoji: '📟', name: 'pager' },
      { emoji: '📠', name: 'fax machine office' },
      { emoji: '📺', name: 'television tv' },
      { emoji: '📻', name: 'radio music' },
      { emoji: '🎙️', name: 'studio microphone recording' },
      { emoji: '🎚️', name: 'level slider audio' },
      { emoji: '🎛️', name: 'control knobs' },
      { emoji: '🧭', name: 'compass navigation' },
      { emoji: '⏱️', name: 'stopwatch timer' },
      { emoji: '⏲️', name: 'timer clock' },
      { emoji: '🕰️', name: 'mantelpiece clock' },
      { emoji: '⏰', name: 'alarm clock' },
      { emoji: '🛢️', name: 'oil drum' },
      { emoji: '🛎️', name: 'bellhop bell' },
      { emoji: '🔑', name: 'key unlock' },
      { emoji: '🗝️', name: 'old key antique' },
      { emoji: '🔨', name: 'hammer tool' },
      { emoji: '🪓', name: 'axe tool' },
      { emoji: '⛏️', name: 'pick mining' },
      { emoji: '⚒️', name: 'hammer and pick' },
      { emoji: '🛠️', name: 'hammer and wrench' },
      { emoji: '🗡️', name: 'dagger knife' },
      { emoji: '⚔️', name: 'crossed swords' },
      { emoji: '🔫', name: 'pistol gun' },
      { emoji: '🛡️', name: 'shield protection' },
      { emoji: '🔧', name: 'wrench tool' },
      { emoji: '🔩', name: 'nut and bolt' },
      { emoji: '⚙️', name: 'gear mechanical' },
      { emoji: '🗜️', name: 'clamp compression' },
      { emoji: '⚖️', name: 'balance scale justice' },
      { emoji: '🔗', name: 'link chain' },
      { emoji: '⛓️', name: 'chains' },
      { emoji: '🧰', name: 'toolbox tools' },
      { emoji: '🧲', name: 'magnet attraction' },
      { emoji: '⚗️', name: 'alembic chemistry' },
      { emoji: '🧪', name: 'test tube experiment' },
      { emoji: '🧫', name: 'petri dish biology' },
      { emoji: '🧬', name: 'dna genetics' },
      { emoji: '🔬', name: 'microscope science' },
      { emoji: '🔭', name: 'telescope astronomy' },
      { emoji: '📡', name: 'satellite antenna' },
      { emoji: '💉', name: 'syringe medical' },
      { emoji: '🩸', name: 'drop of blood' },
      { emoji: '💊', name: 'pill medicine' },
      { emoji: '🩹', name: 'adhesive bandage' },
      { emoji: '🩺', name: 'stethoscope doctor' },
      { emoji: '🚪', name: 'door entrance' },
      { emoji: '🛏️', name: 'bed sleep' },
      { emoji: '🛋️', name: 'couch and lamp' },
      { emoji: '🪑', name: 'chair seat' },
      { emoji: '🚽', name: 'toilet bathroom' },
      { emoji: '🚿', name: 'shower bath' },
      { emoji: '🛁', name: 'bathtub bath' },
      { emoji: '🪒', name: 'razor shave' },
      { emoji: '🧴', name: 'lotion bottle' },
      { emoji: '🧷', name: 'safety pin' },
      { emoji: '🧹', name: 'broom cleaning' },
      { emoji: '🧺', name: 'basket container' },
      { emoji: '🧻', name: 'roll of paper' },
      { emoji: '🧼', name: 'soap cleaning' },
      { emoji: '🧽', name: 'sponge cleaning' },
      { emoji: '🧯', name: 'fire extinguisher' },
      { emoji: '🛒', name: 'shopping cart' },
      { emoji: '🚬', name: 'cigarette smoking' },
      { emoji: '⚰️', name: 'coffin funeral' },
      { emoji: '⚱️', name: 'funeral urn' },
      { emoji: '🗿', name: 'moai statue' },
      { emoji: '🏺', name: 'amphora vase' },
      { emoji: '🔮', name: 'crystal ball fortune' },
      { emoji: '📿', name: 'prayer beads' },
      { emoji: '🧿', name: 'nazar amulet' },
      { emoji: '💎', name: 'gem stone diamond' },
      { emoji: '🔪', name: 'kitchen knife' },
      { emoji: '🏺', name: 'amphora' },
      { emoji: '🗺️', name: 'world map' },
      { emoji: '🧱', name: 'brick construction' },
      { emoji: '🔨', name: 'hammer' },
      { emoji: '🪓', name: 'axe' },
      { emoji: '⛏️', name: 'pick' },
      { emoji: '⚒️', name: 'hammer and pick' },
      { emoji: '🛠️', name: 'hammer and wrench' },
      { emoji: '🗡️', name: 'dagger' },
      { emoji: '⚔️', name: 'crossed swords' },
      { emoji: '🔫', name: 'water pistol' },
      { emoji: '🛡️', name: 'shield' },
      { emoji: '🔧', name: 'wrench' },
      { emoji: '🔩', name: 'nut and bolt' },
      { emoji: '⚙️', name: 'gear' },
      { emoji: '🗜️', name: 'clamp' },
      { emoji: '⚖️', name: 'balance scale' },
      { emoji: '🔗', name: 'link' },
      { emoji: '⛓️', name: 'chains' },
      { emoji: '🧰', name: 'toolbox' },
      { emoji: '🧲', name: 'magnet' },
      { emoji: '⚗️', name: 'alembic' },
      { emoji: '🧪', name: 'test tube' },
      { emoji: '🧫', name: 'petri dish' },
      { emoji: '🧬', name: 'dna' },
      { emoji: '🔬', name: 'microscope' },
      { emoji: '🔭', name: 'telescope' },
      { emoji: '📡', name: 'satellite' },
      { emoji: '💉', name: 'syringe' },
      { emoji: '🩸', name: 'drop of blood' },
      { emoji: '💊', name: 'pill' },
      { emoji: '🩹', name: 'adhesive bandage' },
      { emoji: '🩺', name: 'stethoscope' },
      { emoji: '🚪', name: 'door' },
      { emoji: '🛏️', name: 'bed' },
      { emoji: '🛋️', name: 'couch and lamp' },
      { emoji: '🪑', name: 'chair' },
      { emoji: '🚽', name: 'toilet' },
      { emoji: '🚿', name: 'shower' },
      { emoji: '🛁', name: 'bathtub' },
      { emoji: '🪒', name: 'razor' },
      { emoji: '🧴', name: 'lotion bottle' },
      { emoji: '🧷', name: 'safety pin' },
      { emoji: '🧹', name: 'broom' },
      { emoji: '🧺', name: 'basket' },
      { emoji: '🧻', name: 'roll of paper' },
      { emoji: '🧼', name: 'soap' },
      { emoji: '🧽', name: 'sponge' },
      { emoji: '🧯', name: 'fire extinguisher' },
      { emoji: '🛒', name: 'shopping cart' },
      { emoji: '🚬', name: 'cigarette' },
      { emoji: '⚰️', name: 'coffin' },
      { emoji: '⚱️', name: 'funeral urn' },
      { emoji: '🗿', name: 'moai' },
      { emoji: '🏺', name: 'amphora' },
      { emoji: '🔮', name: 'crystal ball' },
      { emoji: '📿', name: 'prayer beads' },
      { emoji: '🧿', name: 'nazar amulet' },
      { emoji: '💎', name: 'gem stone' },
      { emoji: '🔪', name: 'kitchen knife' },
      { emoji: '🏺', name: 'amphora' },
      { emoji: '🗺️', name: 'world map' },
      { emoji: '🧱', name: 'brick' }
    ]
  },
  symbols: {
    name: 'Symbols',
    icon: 'Sparkles',
    emojis: [
      { emoji: '❤️', name: 'red heart' },
      { emoji: '🧡', name: 'orange heart' },
      { emoji: '💛', name: 'yellow heart' },
      { emoji: '💚', name: 'green heart' },
      { emoji: '💙', name: 'blue heart' },
      { emoji: '💜', name: 'purple heart' },
      { emoji: '🖤', name: 'black heart' },
      { emoji: '🤍', name: 'white heart' },
      { emoji: '🤎', name: 'brown heart' },
      { emoji: '💔', name: 'broken heart' },
      { emoji: '❣️', name: 'heart exclamation' },
      { emoji: '💕', name: 'two hearts' },
      { emoji: '💞', name: 'revolving hearts' },
      { emoji: '💓', name: 'beating heart' },
      { emoji: '💗', name: 'growing heart' },
      { emoji: '💖', name: 'sparkling heart' },
      { emoji: '💘', name: 'heart with arrow' },
      { emoji: '💝', name: 'heart with ribbon' },
      { emoji: '💟', name: 'heart decoration' },
      { emoji: '☮️', name: 'peace symbol' },
      { emoji: '✝️', name: 'latin cross' },
      { emoji: '☪️', name: 'star and crescent' },
      { emoji: '🕉', name: 'om' },
      { emoji: '☸️', name: 'wheel of dharma' },
      { emoji: '✡️', name: 'star of David' },
      { emoji: '🔯', name: 'dotted six-pointed star' },
      { emoji: '🕎', name: 'menorah' },
      { emoji: '☯️', name: 'yin yang' },
      { emoji: '☦️', name: 'orthodox cross' },
      { emoji: '🛐', name: 'place of worship' },
      { emoji: '⛎', name: 'ophiuchus' },
      { emoji: '♈', name: 'aries' },
      { emoji: '♉', name: 'taurus' },
      { emoji: '♊', name: 'gemini' },
      { emoji: '♋', name: 'cancer' },
      { emoji: '♌', name: 'leo' },
      { emoji: '♍', name: 'virgo' },
      { emoji: '♎', name: 'libra' },
      { emoji: '♏', name: 'scorpio' },
      { emoji: '♐', name: 'sagittarius' },
      { emoji: '♑', name: 'capricorn' },
      { emoji: '♒', name: 'aquarius' },
      { emoji: '♓', name: 'pisces' },
      { emoji: '🆔', name: 'id button' },
      { emoji: '⚛️', name: 'atom symbol' },
      { emoji: '🉑', name: 'japanese acceptable button' },
      { emoji: '☢️', name: 'radioactive' },
      { emoji: '☣️', name: 'biohazard' },
      { emoji: '📴', name: 'mobile phone off' },
      { emoji: '📳', name: 'vibration mode' },
      { emoji: '🈶', name: 'japanese not free of charge button' },
      { emoji: '🈚', name: 'japanese free of charge button' },
      { emoji: '🈸', name: 'japanese application button' },
      { emoji: '🈺', name: 'japanese open for business button' },
      { emoji: '🈷️', name: 'japanese monthly amount button' },
      { emoji: '✴️', name: 'eight-pointed star' },
      { emoji: '🆚', name: 'vs button' },
      { emoji: '💮', name: 'white flower' },
      { emoji: '🉐', name: 'japanese bargain button' },
      { emoji: '🈹', name: 'japanese discount button' },
      { emoji: '🈲', name: 'japanese prohibited button' },
      { emoji: '🅰️', name: 'a button blood type' },
      { emoji: '🅱️', name: 'b button blood type' },
      { emoji: '🆎', name: 'ab button blood type' },
      { emoji: '🆑', name: 'cl button' },
      { emoji: '🅾️', name: 'o button blood type' },
      { emoji: '🆘', name: 'sos button' },
      { emoji: '❌', name: 'cross mark' },
      { emoji: '⭕', name: 'hollow red circle' },
      { emoji: '🛑', name: 'stop sign' },
      { emoji: '⛔', name: 'no entry' },
      { emoji: '📛', name: 'name badge' },
      { emoji: '🚫', name: 'prohibited' },
      { emoji: '💯', name: 'hundred points' },
      { emoji: '🔞', name: 'no one under eighteen' },
      { emoji: '📵', name: 'no mobile phones' },
      { emoji: '🚯', name: 'no littering' },
      { emoji: '🚱', name: 'non-potable water' },
      { emoji: '🚳', name: 'no bicycles' },
      { emoji: '🚷', name: 'no pedestrians' },
      { emoji: '🚸', name: 'children crossing' },
      { emoji: '⛍', name: 'shopping bags' },
      { emoji: '♿', name: 'wheelchair symbol' },
      { emoji: '🚭', name: 'no smoking' },
      { emoji: '❗', name: 'exclamation mark' },
      { emoji: '❕', name: 'white exclamation mark' },
      { emoji: '❓', name: 'question mark' },
      { emoji: '❔', name: 'white question mark' },
      { emoji: '‼️', name: 'double exclamation mark' },
      { emoji: '⁉️', name: 'exclamation question mark' },
      { emoji: '🔅', name: 'dim button' },
      { emoji: '🔆', name: 'bright button' },
      { emoji: '🔱', name: 'trident emblem' },
      { emoji: '📛', name: 'name badge' },
      { emoji: '🔰', name: 'japanese symbol for beginner' },
      { emoji: '🔠', name: 'input latin uppercase' },
      { emoji: '🔡', name: 'input latin lowercase' },
      { emoji: '🔢', name: 'input numbers' },
      { emoji: '🔣', name: 'input symbols' },
      { emoji: '🔤', name: 'input latin letters' },
      { emoji: '🅰️', name: 'a button' },
      { emoji: '🆎', name: 'ab button' },
      { emoji: '🅱️', name: 'b button' },
      { emoji: '🆑', name: 'cl button' },
      { emoji: '🅾️', name: 'o button' },
      { emoji: '🆘', name: 'sos button' },
      { emoji: '❌', name: 'cross mark' },
      { emoji: '⭕', name: 'hollow red circle' },
      { emoji: '🛑', name: 'stop sign' },
      { emoji: '⛔', name: 'no entry' },
      { emoji: '📛', name: 'name badge' },
      { emoji: '🚫', name: 'prohibited' },
      { emoji: '💯', name: 'hundred points' },
      { emoji: '🔞', name: 'no one under eighteen' },
      { emoji: '📵', name: 'no mobile phones' },
      { emoji: '🚯', name: 'no littering' },
      { emoji: '🚱', name: 'non-potable water' },
      { emoji: '🚳', name: 'no bicycles' },
      { emoji: '🚷', name: 'no pedestrians' },
      { emoji: '🚸', name: 'children crossing' },
      { emoji: '⛍', name: 'shopping bags' },
      { emoji: '♿', name: 'wheelchair symbol' },
      { emoji: '🚭', name: 'no smoking' },
      { emoji: '❗', name: 'red exclamation mark' },
      { emoji: '❕', name: 'white exclamation mark' },
      { emoji: '❓', name: 'red question mark' },
      { emoji: '❔', name: 'white question mark' },
      { emoji: '‼️', name: 'double exclamation mark' },
      { emoji: '⁉️', name: 'exclamation question mark' },
      { emoji: '🔅', name: 'dim button' },
      { emoji: '🔆', name: 'bright button' },
      { emoji: '🔱', name: 'trident emblem' },
      { emoji: '📛', name: 'name badge' },
      { emoji: '🔰', name: 'japanese symbol for beginner' },
      { emoji: '🔠', name: 'input latin uppercase' },
      { emoji: '🔡', name: 'input latin lowercase' },
      { emoji: '🔢', name: 'input numbers' },
      { emoji: '🔣', name: 'input symbols' },
      { emoji: '🔤', name: 'input latin letters' }
    ]
  },
  flags: {
    name: 'Flags',
    icon: 'Flag',
    emojis: [
      { emoji: '🏁', name: 'chequered flag racing finish' },
      { emoji: '🚩', name: 'triangular flag location' },
      { emoji: '🎌', name: 'crossed flags celebration' },
      { emoji: '🏴', name: 'black flag' },
      { emoji: '🏳️', name: 'white flag surrender' },
      { emoji: '🏳️‍🌈', name: 'rainbow flag pride lgbt' },
      { emoji: '🏳️‍⚧️', name: 'transgender flag' },
      { emoji: '🏴‍☠️', name: 'pirate flag skull crossbones' },
      { emoji: '🇦🇺', name: 'australia flag' },
      { emoji: '🇧🇷', name: 'brazil flag' },
      { emoji: '🇨🇦', name: 'canada flag' },
      { emoji: '🇨🇳', name: 'china flag' },
      { emoji: '🇫🇷', name: 'france flag' },
      { emoji: '🇩🇪', name: 'germany flag' },
      { emoji: '🇮🇳', name: 'india flag' },
      { emoji: '🇮🇹', name: 'italy flag' },
      { emoji: '🇯🇵', name: 'japan flag' },
      { emoji: '🇰🇷', name: 'south korea flag' },
      { emoji: '🇲🇽', name: 'mexico flag' },
      { emoji: '🇳🇱', name: 'netherlands flag' },
      { emoji: '🇷🇺', name: 'russia flag' },
      { emoji: '🇿🇦', name: 'south africa flag' },
      { emoji: '🇪🇸', name: 'spain flag' },
      { emoji: '🇸🇪', name: 'sweden flag' },
      { emoji: '🇨🇭', name: 'switzerland flag' },
      { emoji: '🇹🇷', name: 'turkey flag' },
      { emoji: '🇬🇧', name: 'united kingdom flag' },
      { emoji: '🇺🇸', name: 'united states flag' },
      { emoji: '🇦🇪', name: 'united arab emirates flag' },
      { emoji: '🇦🇷', name: 'argentina flag' },
      { emoji: '🇦🇹', name: 'austria flag' },
      { emoji: '🇧🇪', name: 'belgium flag' },
      { emoji: '🇧🇩', name: 'bangladesh flag' },
      { emoji: '🇧🇬', name: 'bulgaria flag' },
      { emoji: '🇧🇴', name: 'bolivia flag' },
      { emoji: '🇨🇱', name: 'chile flag' },
      { emoji: '🇨🇴', name: 'colombia flag' },
      { emoji: '🇨🇷', name: 'costa rica flag' },
      { emoji: '🇨🇺', name: 'cuba flag' },
      { emoji: '🇨🇿', name: 'czechia flag' },
      { emoji: '🇩🇰', name: 'denmark flag' },
      { emoji: '🇩🇴', name: 'dominican republic flag' },
      { emoji: '🇪🇨', name: 'ecuador flag' },
      { emoji: '🇪🇬', name: 'egypt flag' },
      { emoji: '🇸🇻', name: 'el salvador flag' },
      { emoji: '🇪🇪', name: 'estonia flag' },
      { emoji: '🇪🇹', name: 'ethiopia flag' },
      { emoji: '🇫🇮', name: 'finland flag' },
      { emoji: '🇬🇷', name: 'greece flag' },
      { emoji: '🇬🇹', name: 'guatemala flag' },
      { emoji: '🇭🇳', name: 'honduras flag' },
      { emoji: '🇭🇰', name: 'hong kong flag' },
      { emoji: '🇭🇺', name: 'hungary flag' },
      { emoji: '🇮🇩', name: 'indonesia flag' },
      { emoji: '🇮🇪', name: 'ireland flag' },
      { emoji: '🇮🇱', name: 'israel flag' },
      { emoji: '🇯🇲', name: 'jamaica flag' },
      { emoji: '🇯🇴', name: 'jordan flag' },
      { emoji: '🇰🇪', name: 'kenya flag' },
      { emoji: '🇰🇼', name: 'kuwait flag' },
      { emoji: '🇱🇧', name: 'lebanon flag' },
      { emoji: '🇱🇰', name: 'sri lanka flag' },
      { emoji: '🇱🇹', name: 'lithuania flag' },
      { emoji: '🇱🇺', name: 'luxembourg flag' },
      { emoji: '🇱🇻', name: 'latvia flag' },
      { emoji: '🇲🇦', name: 'morocco flag' },
      { emoji: '🇲🇾', name: 'malaysia flag' },
      { emoji: '🇲🇹', name: 'malta flag' },
      { emoji: '🇲🇲', name: 'myanmar flag' },
      { emoji: '🇳🇬', name: 'nigeria flag' },
      { emoji: '🇳🇴', name: 'norway flag' },
      { emoji: '🇳🇵', name: 'nepal flag' },
      { emoji: '🇳🇿', name: 'new zealand flag' },
      { emoji: '🇵🇦', name: 'panama flag' },
      { emoji: '🇵🇪', name: 'peru flag' },
      { emoji: '🇵🇭', name: 'philippines flag' },
      { emoji: '🇵🇰', name: 'pakistan flag' },
      { emoji: '🇵🇱', name: 'poland flag' },
      { emoji: '🇵🇹', name: 'portugal flag' },
      { emoji: '🇵🇾', name: 'paraguay flag' },
      { emoji: '🇶🇦', name: 'qatar flag' },
      { emoji: '🇷🇴', name: 'romania flag' },
      { emoji: '🇸🇦', name: 'saudi arabia flag' },
      { emoji: '🇸🇬', name: 'singapore flag' },
      { emoji: '🇸🇰', name: 'slovakia flag' },
      { emoji: '🇸🇮', name: 'slovenia flag' },
      { emoji: '🇹🇭', name: 'thailand flag' },
      { emoji: '🇹🇳', name: 'tunisia flag' },
      { emoji: '🇹🇼', name: 'taiwan flag' },
      { emoji: '🇺🇦', name: 'ukraine flag' },
      { emoji: '🇺🇾', name: 'uruguay flag' },
      { emoji: '🇻🇪', name: 'venezuela flag' },
      { emoji: '🇻🇳', name: 'vietnam flag' },
      { emoji: '🇿🇲', name: 'zambia flag' },
      { emoji: '🇿🇼', name: 'zimbabwe flag' },
      { emoji: '🇦🇫', name: 'afghanistan flag' },
      { emoji: '🇦🇱', name: 'albania flag' },
      { emoji: '🇩🇿', name: 'algeria flag' },
      { emoji: '🇦🇴', name: 'angola flag' },
      { emoji: '🇦🇲', name: 'armenia flag' },
      { emoji: '🇦🇿', name: 'azerbaijan flag' },
      { emoji: '🇧🇭', name: 'bahrain flag' },
      { emoji: '🇧🇾', name: 'belarus flag' },
      { emoji: '🇧🇿', name: 'belize flag' },
      { emoji: '🇧🇯', name: 'benin flag' },
      { emoji: '🇧🇹', name: 'bhutan flag' },
      { emoji: '🇧🇼', name: 'botswana flag' },
      { emoji: '🇧🇦', name: 'bosnia herzegovina flag' },
      { emoji: '🇧🇳', name: 'brunei flag' },
      { emoji: '🇧🇫', name: 'burkina faso flag' },
      { emoji: '🇧🇮', name: 'burundi flag' },
      { emoji: '🇰🇭', name: 'cambodia flag' },
      { emoji: '🇨🇲', name: 'cameroon flag' },
      { emoji: '🇨🇻', name: 'cape verde flag' },
      { emoji: '🇨🇫', name: 'central african republic flag' },
      { emoji: '🇹🇩', name: 'chad flag' },
      { emoji: '🇰🇲', name: 'comoros flag' },
      { emoji: '🇨🇬', name: 'congo brazzaville flag' },
      { emoji: '🇨🇩', name: 'congo kinshasa flag' },
      { emoji: '🇭🇷', name: 'croatia flag' },
      { emoji: '🇨🇾', name: 'cyprus flag' },
      { emoji: '🇩🇯', name: 'djibouti flag' },
      { emoji: '🇪🇷', name: 'eritrea flag' },
      { emoji: '🇸🇿', name: 'eswatini flag' },
      { emoji: '🇫🇯', name: 'fiji flag' },
      { emoji: '🇬🇦', name: 'gabon flag' },
      { emoji: '🇬🇲', name: 'gambia flag' },
      { emoji: '🇬🇪', name: 'georgia flag' },
      { emoji: '🇬🇭', name: 'ghana flag' },
      { emoji: '🇬🇼', name: 'guinea bissau flag' },
      { emoji: '🇬🇾', name: 'guyana flag' },
      { emoji: '🇭🇹', name: 'haiti flag' },
      { emoji: '🇮🇸', name: 'iceland flag' },
      { emoji: '🇮🇷', name: 'iran flag' },
      { emoji: '🇮🇶', name: 'iraq flag' },
      { emoji: '🇯🇪', name: 'jersey flag' },
      { emoji: '🇯🇰', name: 'jordan flag' },
      { emoji: '🇰🇿', name: 'kazakhstan flag' },
      { emoji: '🇰🇮', name: 'kiribati flag' },
      { emoji: '🇽🇰', name: 'kosovo flag' },
      { emoji: '🇰🇬', name: 'kyrgyzstan flag' },
      { emoji: '🇱🇦', name: 'laos flag' },
      { emoji: '🇱🇸', name: 'lesotho flag' },
      { emoji: '🇱🇷', name: 'liberia flag' },
      { emoji: '🇱🇾', name: 'libya flag' },
      { emoji: '🇱🇮', name: 'liechtenstein flag' },
      { emoji: '🇲🇬', name: 'madagascar flag' },
      { emoji: '🇲🇼', name: 'malawi flag' },
      { emoji: '🇲🇱', name: 'mali flag' },
      { emoji: '🇲🇭', name: 'marshall islands flag' },
      { emoji: '🇲🇷', name: 'mauritania flag' },
      { emoji: '🇲🇺', name: 'mauritius flag' },
      { emoji: '🇲🇩', name: 'moldova flag' },
      { emoji: '🇲🇨', name: 'monaco flag' },
      { emoji: '🇲🇪', name: 'montenegro flag' },
      { emoji: '🇲🇿', name: 'mozambique flag' },
      { emoji: '🇳🇦', name: 'namibia flag' },
      { emoji: '🇳🇷', name: 'nauru flag' },
      { emoji: '🇳🇮', name: 'nicaragua flag' },
      { emoji: '🇳🇪', name: 'niger flag' },
      { emoji: '🇰🇵', name: 'north korea flag' },
      { emoji: '🇲🇰', name: 'north macedonia flag' },
      { emoji: '🇴🇲', name: 'oman flag' },
      { emoji: '🇵🇼', name: 'palau flag' },
      { emoji: '🇵🇬', name: 'papua new guinea flag' },
      { emoji: '🇷🇸', name: 'serbia flag' },
      { emoji: '🇸🇨', name: 'seychelles flag' },
      { emoji: '🇸🇱', name: 'sierra leone flag' },
      { emoji: '🇸🇧', name: 'solomon islands flag' },
      { emoji: '🇸🇴', name: 'somalia flag' },
      { emoji: '🇸🇸', name: 'south sudan flag' },
      { emoji: '🇱🇨', name: 'st lucia flag' },
      { emoji: '🇻🇨', name: 'st vincent grenadines flag' },
      { emoji: '🇸🇩', name: 'sudan flag' },
      { emoji: '🇸🇷', name: 'suriname flag' },
      { emoji: '🇸🇾', name: 'syria flag' },
      { emoji: '🇹🇯', name: 'tajikistan flag' },
      { emoji: '🇹🇿', name: 'tanzania flag' },
      { emoji: '🇹🇱', name: 'timor leste flag' },
      { emoji: '🇹🇬', name: 'togo flag' },
      { emoji: '🇹🇴', name: 'tonga flag' },
      { emoji: '🇹🇹', name: 'trinidad tobago flag' },
      { emoji: '🇹🇲', name: 'turkmenistan flag' },
      { emoji: '🇹🇻', name: 'tuvalu flag' },
      { emoji: '🇺🇬', name: 'uganda flag' },
      { emoji: '🇺🇿', name: 'uzbekistan flag' },
      { emoji: '🇻🇺', name: 'vanuatu flag' },
      { emoji: '🇻🇦', name: 'vatican city flag' },
      { emoji: '🇾🇪', name: 'yemen flag' },
      { emoji: '🇦🇩', name: 'andorra flag' },
      { emoji: '🇦🇬', name: 'antigua barbuda flag' },
      { emoji: '🇧🇸', name: 'bahamas flag' },
      { emoji: '🇧🇧', name: 'barbados flag' },
      { emoji: '🇧🇿', name: 'belize flag' },
      { emoji: '🇧🇹', name: 'bhutan flag' },
      { emoji: '🇻🇬', name: 'british virgin islands flag' },
      { emoji: '🇰🇾', name: 'cayman islands flag' },
      { emoji: '🇨🇰', name: 'cook islands flag' },
      { emoji: '🇩🇲', name: 'dominica flag' },
      { emoji: '🇬🇩', name: 'grenada flag' },
      { emoji: '🇬🇾', name: 'guyana flag' },
      { emoji: '🇭🇹', name: 'haiti flag' },
      { emoji: '🇯🇲', name: 'jamaica flag' },
      { emoji: '🇰🇮', name: 'kiribati flag' },
      { emoji: '🇲🇭', name: 'marshall islands flag' },
      { emoji: '🇫🇲', name: 'micronesia flag' },
      { emoji: '🇲🇸', name: 'montserrat flag' },
      { emoji: '🇳🇷', name: 'nauru flag' },
      { emoji: '🇳🇺', name: 'niue flag' },
      { emoji: '🇵🇼', name: 'palau flag' },
      { emoji: '🇵🇳', name: 'pitcairn islands flag' },
      { emoji: '🇰🇳', name: 'st kitts nevis flag' },
      { emoji: '🇱🇨', name: 'st lucia flag' },
      { emoji: '🇻🇨', name: 'st vincent grenadines flag' },
      { emoji: '🇼🇸', name: 'samoa flag' },
      { emoji: '🇸🇲', name: 'san marino flag' },
      { emoji: '🇸🇹', name: 'sao tome principe flag' },
      { emoji: '🇸🇧', name: 'solomon islands flag' },
      { emoji: '🇹🇰', name: 'tokelau flag' },
      { emoji: '🇹🇴', name: 'tonga flag' },
      { emoji: '🇹🇻', name: 'tuvalu flag' },
      { emoji: '🇻🇺', name: 'vanuatu flag' },
      { emoji: '🇦🇮', name: 'anguilla flag' },
      { emoji: '🇦🇶', name: 'antarctica flag' },
      { emoji: '🇦🇼', name: 'aruba flag' },
      { emoji: '🇧🇲', name: 'bermuda flag' },
      { emoji: '🇧🇶', name: 'caribbean netherlands flag' },
      { emoji: '🇮🇴', name: 'british indian ocean territory flag' },
      { emoji: '🇻🇬', name: 'british virgin islands flag' },
      { emoji: '🇮🇨', name: 'canary islands flag' },
      { emoji: '🇪🇦', name: 'ceuta melilla flag' },
      { emoji: '🇨🇵', name: 'clipperton island flag' },
      { emoji: '🇨🇼', name: 'curacao flag' },
      { emoji: '🇬🇫', name: 'french guiana flag' },
      { emoji: '🇹🇫', name: 'french southern territories flag' },
      { emoji: '🇬🇮', name: 'gibraltar flag' },
      { emoji: '🇬🇱', name: 'greenland flag' },
      { emoji: '🇬🇵', name: 'guadeloupe flag' },
      { emoji: '🇬🇺', name: 'guam flag' },
      { emoji: '🇬🇬', name: 'guernsey flag' },
      { emoji: '🇭🇲', name: 'heard mcdonald islands flag' },
      { emoji: '🇯🇪', name: 'jersey flag' },
      { emoji: '🇲🇪', name: 'montenegro flag' },
      { emoji: '🇲🇸', name: 'montserrat flag' },
      { emoji: '🇾🇹', name: 'mayotte flag' },
      { emoji: '🇳🇨', name: 'new caledonia flag' },
      { emoji: '🇳🇫', name: 'norfolk island flag' },
      { emoji: '🇲🇵', name: 'northern mariana islands flag' },
      { emoji: '🇵🇫', name: 'french polynesia flag' },
      { emoji: '🇵🇷', name: 'puerto rico flag' },
      { emoji: '🇷🇪', name: 'reunion flag' },
      { emoji: '🇸🇭', name: 'st helena flag' },
      { emoji: '🇵🇲', name: 'st pierre miquelon flag' },
      { emoji: '🇸🇽', name: 'sint maarten flag' },
      { emoji: '🇬🇸', name: 'south georgia sandwich islands flag' },
      { emoji: '🇹🇨', name: 'turks caicos islands flag' },
      { emoji: '🇺🇲', name: 'us outlying islands flag' },
      { emoji: '🇻🇮', name: 'us virgin islands flag' },
      { emoji: '🇼🇫', name: 'wallis futuna flag' }
    ]
  }
}